name = "skeb-info"
compatibility_date = "2025-04-28"
main = "worker.js"
type = "esmodule"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.